### ISSUE TITLE
deleting an event crf results in oops page

### ISSUE THREAD

**Issue by GerbenRienk** [reliatec-gmbh/LibreClinica#111]
**lc v.0.5.0 tomcat 8.5.50.0 jdk 1.8.0_231-b11**

When I try to delete a crf in form **View Subject** by clicking the white cross on red background I get the oops-page.

In catalina.out is the following message:
javax.persistence.TransactionRequiredException: Executing an update/delete query
        at org.hibernate.internal.AbstractSharedSessionContract.checkTransactionNeededForUpdateOperation(AbstractSharedSessionContract.java:398)
        at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1604)
        at org.akaza.openclinica.dao.hibernate.DynamicsItemFormMetadataDao.delete(DynamicsItemFormMetadataDao.java:235)
        at org.akaza.openclinica.dao.hibernate.DynamicsItemFormMetadataDao$$FastClassBySpringCGLIB$$c501d5c7.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
        at org.akaza.openclinica.dao.hibernate.DynamicsItemFormMetadataDao$$EnhancerBySpringCGLIB$$7790a10f.delete(<generated>)
        at org.akaza.openclinica.control.admin.DeleteEventCRFServlet.processRequest(DeleteEventCRFServlet.java:155)
        at org.akaza.openclinica.control.core.SecureController.process(SecureController.java:591)
 etc.

**Comment by GerbenRienk** [comment]
This also happens with the v.0.6.0 release, unfortunately.
Error is now written to the libreclinica.log:

 01/22 21:28:23 [] FTP INFO  lctest_techadmin o.a.o.c.c.SecureController:151 - submit to delete the event CRF from event
 01/22 21:28:23 [] FTP ERROR lctest_techadmin o.a.o.c.c.SecureController:605 - Process is throwing exception:
 javax.persistence.TransactionRequiredException: Executing an update/delete query
        at org.hibernate.internal.AbstractSharedSessionContract.checkTransactionNeededForUpdateOperation(AbstractSharedSessionContract.java:398)
        at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1604)
        at org.akaza.openclinica.dao.hibernate.DynamicsItemFormMetadataDao.delete(DynamicsItemFormMetadataDao.java:242)
        at org.akaza.openclinica.dao.hibernate.DynamicsItemFormMetadataDao$$FastClassBySpringCGLIB$$c501d5c7.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
        at org.akaza.openclinica.dao.hibernate.DynamicsItemFormMetadataDao$$EnhancerBySpringCGLIB$$59cd7190.delete(<generated>)
        at org.akaza.openclinica.control.admin.DeleteEventCRFServlet.processRequest(DeleteEventCRFServlet.java:155)
        at org.akaza.openclinica.control.core.SecureController.process(SecureController.java:589)
        at org.akaza.openclinica.control.core.SecureController.doPost(SecureController.java:649)
etc.

**Comment by toskrip** [comment]
Cleanup of hibernate syntax and adding @Transactional annotation on delete methods of Dao classes that are involved in the DeleteEventCRFServlet request should fix the issue.
