### ISSUE TITLE
lc v.0.6.0 exporting a dataset results in oops

### ISSUE THREAD

**Issue by GerbenRienk** [reliatec-gmbh/LibreClinica#122]
**libre v.0.6.0 tomcat 8.5.50 jdk 1.8.0_231-b11**
When exporting a dataset in any format this results in an oops page.
In lcw060.2020-01-26.log is the following:
01/26 13:52:16 [] FTP INFO  lctest_techadmin o.a.o.c.c.SecureController:509 - action is blank
 01/26 13:52:16 [] FTP INFO  lctest_techadmin o.a.o.c.c.SecureController:511 - just set dataset to request
 01/26 13:52:16 [] FTP WARN  lctest_techadmin o.a.o.c.c.SecureController:542 -
 01/26 13:52:16 [] FTP WARN  lctest_techadmin o.a.o.c.c.SecureController:543 - file list length: 0
 01/26 13:52:16 [] FTP WARN  lctest_techadmin o.a.o.c.c.SecureController:584 - just set file list to request, sending to page
 01/26 13:52:39 [] FTP ERROR lctest_techadmin o.a.o.c.ExtractController:184 - Error while accessing job date:
 org.quartz.JobPersistenceException: Couldn't store job: ERROR: column "job_data" is of type oid but expression is of type bytea
  Hint: You will need to rewrite or cast the expression.
  Position: 221
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeJob(JobStoreSupport.java:1118)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$2.executeVoid(JobStoreSupport.java:1062)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$VoidTransactionCallback.execute(JobStoreSupport.java:3719)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$VoidTransactionCallback.execute(JobStoreSupport.java:3717)
        at org.quartz.impl.jdbcjobstore.JobStoreCMT.executeInLock(JobStoreCMT.java:245)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeJobAndTrigger(JobStoreSupport.java:1058)
etc.

Full log: 
[lcw060.2020-01-26.log](https://github.com/reliatec-gmbh/LibreClinica/files/4113469/lcw060.2020-01-26.log)

**Comment by toskrip** [comment]
table: oc_qrtz_job_details; column: job_data (oid -> bytea)
table: oc_qrtz_job_details: column: job_data (oid -> bytea)

I think we need to adapt the update_to_spring_5.xml changelog for liquibase, to fix the initialisation of new database.
