### ISSUE TITLE
creating an import job results in oops

### ISSUE THREAD

**Issue by GerbenRienk** [reliatec-gmbh/LibreClinica#123]
lc 0.6.0 

creating an importjob results in an error.
In lcw060.2020-01-26.log:
 01/26 14:36:39 [] FTP INFO  lctest_techadmin o.a.o.c.c.SecureController:154 - found no validation errors, continuing
 01/26 14:36:39 [] FTP ERROR lctest_techadmin o.a.o.c.c.SecureController:605 - Process is throwing exception:
 java.lang.ClassCastException: org.quartz.TriggerBuilder cannot be cast to org.quartz.SimpleTrigger
        at org.akaza.openclinica.web.job.TriggerService.generateImportTrigger(TriggerService.java:162)
        at org.akaza.openclinica.web.job.TriggerService.generateImportTrigger(TriggerService.java:135)
        at org.akaza.openclinica.control.admin.CreateJobImportServlet.processRequest(CreateJobImportServlet.java:158)
        at org.akaza.openclinica.control.core.SecureController.process(SecureController.java:589)
        at org.akaza.openclinica.control.core.SecureController.doPost(SecureController.java:649)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
etc.

[create_import_job_errors.log](https://github.com/reliatec-gmbh/LibreClinica/files/4113553/create_import_job_errors.log)

**Comment by toskrip** [comment]
I reproduce this issue. I think I can fix it.
