### ISSUE TITLE
running a rule in a study without item data results in an oops

### ISSUE THREAD

**Issue by GerbenRienk** [reliatec-gmbh/LibreClinica#127]
In a study that has rules and subjects, running a rule manually, that is from ViewRuleAssignment RunRuleSet, results in an oops, when there are no item-data for this rule.

 01/27 13:47:04 [] FTP ERROR lctest_techadmin o.a.o.c.c.SecureController:605 - Process is throwing exception:
 java.lang.NullPointerException: null
        at org.akaza.openclinica.service.rule.RuleSetService.filterRuleSetsByGroupOrdinal(RuleSetService.java:861)
        at org.akaza.openclinica.service.rule.RuleSetService.runRulesInBulk(RuleSetService.java:340)
        at org.akaza.openclinica.service.rule.RuleSetService$$FastClassBySpringCGLIB$$8349998f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
        at org.akaza.openclinica.service.rule.RuleSetService$$EnhancerBySpringCGLIB$$c6a3e2aa.runRulesInBulk(<generated>)
        at org.akaza.openclinica.control.submit.RunRuleSetServlet.processRequest(RunRuleSetServlet.java:75)
etc.

[run_rule_with_no_item_data.log](https://github.com/reliatec-gmbh/LibreClinica/files/4117175/run_rule_with_no_item_data.log)

**Comment by toskrip** [comment]
Reproduced. I will see if I can fix this.
