### ISSUE TITLE
Audit user activity - data table filter produces error

### ISSUE THREAD

**Issue by toskrip** [reliatec-gmbh/LibreClinica#200]
**Description:**
In administration of users, the administrator has the ability to audit user activity. This data table provides GUI filter but for User Name and Details columns if there is no entry matching the filter the Oops! page is display instead of empty data table.

**Requirements:**
None. Just basic installation with at least one administrator user.

**Steps to follow:**
1. login
2. go to Tasks/Administration/Users
3. click on Audit User Activity
4. enter non existing user (or user who was never logged in) into User Name filter (the same applies for Details filter) and press enter

**Expected result:**
Empty data table is displayed (There were no results found).

**Actual result:**
Oops! An error has occurred page is displayed.

**Comment by tomhickerson** [comment]
the actual bug is being thrown here:
```
11/27 13:30:17 [/usr/local/tomcat/webapps/libreclinica/] FTP ERROR root o.a.o.c.c.SecureController:605 - Process is throwing exception:
 java.lang.ClassCastException: class java.util.Collections$EmptyList cannot be cast to class java.util.ArrayList (java.util.Collections$EmptyList and java.util.ArrayList are in module java.base of loader 'bootstrap')
        at org.akaza.openclinica.dao.hibernate.AuditUserLoginDao.getWithFilterAndSort(AuditUserLoginDao.java:45)
        at org.akaza.openclinica.dao.hibernate.AuditUserLoginDao$$FastClassBySpringCGLIB$$82cefe1e.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
        at org.akaza.openclinica.dao.hibernate.AuditUserLoginDao$$EnhancerBySpringCGLIB$$dc636f0a.getWithFilterAndSort(<generated>)
        at org.akaza.openclinica.control.admin.AuditUserLoginTableFactory.setDataAndLimitVariables(AuditUserLoginTableFactory.java:113)
        at org.akaza.openclinica.control.AbstractTableFactory.createTable(AbstractTableFactory.java:68)
        at org.akaza.openclinica.control.admin.AuditUserActivityServlet.processRequest(AuditUserActivityServlet.java:60)
        at org.akaza.openclinica.control.core.SecureController.process(SecureController.java:589)
        at org.akaza.openclinica.control.core.SecureController.doGet(SecureController.java:633)
```
		
probably you will need to execute a try-catch like the following on that code:

```
		try {
			criteria = filter.execute(criteria);
		} catch (IllegalArgumentException ex) {  // or something else
			return new ArrayList<AuditUserLoginBean>();
		}
```
I can try to generate a pull request for it sometime next week?

**Comment by toskrip** [comment]
Seems like this is no longer an issue in current lc-develop branch. Probably it was fixed with DAO refactoring in lc-refactor.
