### ISSUE TITLE
Editing one's own user profile results in an Oops Page

### ISSUE THREAD

**Issue by tomhickerson** [reliatec-gmbh/LibreClinica#208]
**Description:**
A freshly-deployed instance of LibreClinica, which is not connected to LDAP, throws errors when a user tries to edit their own profile.

**Requirements:**
A recent deploy of Libreclinica, with default LDAP settings in datainfo and very few user accounts (I used root).

**Steps to follow:**
1. Log into a Libreclinica instance as root
2. Click on the profile hyperlink in the upper right hand corner 
3. Attempt to change the email address from openclinica_admin@example.com to something else 
4. Enter the user's password in the 'old password' field and save the form

**Expected result:**
Profile saves successfully.

**Actual result:**
Oops page is shown and the following exception is thrown in the back-end:

```
 11/28 16:41:47 [/usr/local/tomcat/webapps/libreclinica/] FTP ERROR root o.a.o.c.c.SecureController:605 - Process is throwing exception:
 java.lang.NullPointerException: null
        at org.akaza.openclinica.service.user.LdapUserService.searchForUser(LdapUserService.java:157)
        at org.akaza.openclinica.service.user.OpenClinicaLdapUserSearch.searchForUser(OpenClinicaLdapUserSearch.java:30)
        at org.springframework.security.ldap.authentication.BindAuthenticator.authenticate(BindAuthenticator.java:95)
        at org.springframework.security.ldap.authentication.LdapAuthenticationProvider.doAuthentication(LdapAuthenticationProvider.java:187)
        at org.springframework.security.ldap.authentication.AbstractLdapAuthenticationProvider.authenticate(AbstractLdapAuthenticationProvider.java:85)
        at org.akaza.openclinica.core.SecurityManager.verifyPassword(SecurityManager.java:70)
        at org.akaza.openclinica.control.login.UpdateProfileServlet.confirmProfile(UpdateProfileServlet.java:151)
        at org.akaza.openclinica.control.login.UpdateProfileServlet.processRequest(UpdateProfileServlet.java:70)
        at org.akaza.openclinica.control.core.SecureController.process(SecureController.java:589)
        at org.akaza.openclinica.control.core.SecureController.doPost(SecureController.java:649)

```

**Server Setup:**
 - CentOS 7
 - Tomcat 9
 - OpenJDK 11
 - Postgres 11

**Comment by chae-reliatec** [comment]
Hi Tom

Thank you for reporting this issue. We'll try to reproduce it.

Regards,
Christian

**Comment by tomhickerson** [comment]
Hi Christian, 

It was actually built from my fork of lc-develop, so it still said 1.0 on the pom file/compiled jar file.  

Hope that helps, Tom

**Comment by chae-reliatec** [comment]
Hi Tom

I tested LibreClinica from the LibreClinica lc-develop branch with an installation following the officialy recommended software stack but cannot reproduce the error. From the error message it seems like the instance variable ldapTemplate from LdapUserService is null. It should be initialized by the init() method. Can you check if this is the case for your installation?

Regards,
Christian

**Comment by tomhickerson** [comment]
Hi Christian,

As discovered on the PR for #200 , I actually did not compile my war file with Java 8, and had removed the annotation which loads the ldapTemplate.  Compiling with a later version of the JDK forces us to remove the annotation and introduce this regression.  I'll close this for now, but you should keep it in mind when upgrading the JDK.

Thanks, Tom
