### ISSUE TITLE
Installation write issues with current war file

### ISSUE THREAD

**Issue by Diggitysc** [reliatec-gmbh/LibreClinica#362]
Greetings, 

I am attempting to create a local instance to demo libreclinica for potential further use. 

However following the directions from https://www.libreclinica.org/documentation/install.html and using both the 1.1 and 1.2 war files I run into the follow write error when starting tomcat: 

SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.akaza.openclinica.dao.core.OCContextLoaderListener]
        org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.beans.factory.config.PropertyPlaceholderConfigurer#0' defined in class path resource [org/akaza/openclinica/applicationContext-core-spring.xml]: Cannot resolve reference to bean 'dataInfoProperties' while setting bean property 'properties'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'coreResources' defined in class path resource [org/akaza/openclinica/applicationContext-core-spring.xml]: Initialization of bean failed; nested exception is org.akaza.openclinica.exception.OpenClinicaSystemException: Copying files, Could not create direcotry: /usr/share/tomcat9/libreclinica.data/xslt.
                at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:378)
                at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1648)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1400)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:575)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)

When I create  /usr/share/tomcat9/libreclinica.data/xslt it has the same error for the next file down the line. It doesn't seem to matter what permissions I provide the base directory (777 etc) 

Please advise

**Comment by toskrip** [comment]
Hi,

Normally I use custom (non-standard) installation procedure. However when I have a quick look at the manual I have a feeling that there is one step missing.  In the step 2. substep 5. you create softlink libreclinica.config to point to real config folder.

I think the same should be done also for the data folder:

`sudo ln -s /usr/share/tomcat9/libreclinica/data/ /usr/share/tomcat9/libreclinica.data`

otherwise tomcat user need to should be owner for those files/folders.
