### ISSUE TITLE
Webservices version 1.1 don't function after migrating libreclinica from 1.1 to 1.2.x

### ISSUE THREAD

**Issue by GerbenRienk** [reliatec-gmbh/LibreClinica#384]
**Description:**
After migrating a database/instance from 1.1.x to 1.2.x the web-services no longer function.

**Requirements:**
A setup that has an instance of libreclinica 1.1.x in combination with working webservices version 1.1.
For documenting this issue we used soapUI version 5.7.2

**Steps to follow:**
1. install an instance of lc, Version: 1.1.0 - Changeset: 7ab59c39e732
1. install an instance of ws 1.1.0
1. create a request to endpoint ws/study/v1 with <v1:listAllRequest></v1:listAllRequest>
1. the response is `<result>Success</result>`
1. now replace lc_110 with lc_120, Version: 1.2.0 - Changeset: 5b8033607f31,letting it point to the same database
1. issue the same request to endpoint ws/study/v1 with <v1:listAllRequest></v1:listAllRequest>

**Expected result:**
We would expect the same response, namely:
`<result>Success</result>`

**Actual result:**
The response is
`<faultstring xml:lang="en">The given column index '28' is not within the allowed range of [1,27].</faultstring>`

**Related (optional):**
If we switch back the web-interface from 1.2.0 to 1.1.0 again, we can no longer login. In the localhost-log there is an entry:
`SEVERE [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-97] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [default] in context with path [/lc_110] threw exception [java.lang.IllegalArgumentException: The given column index '28' is not within the allowed range of [1,27].] with root cause
        java.lang.IllegalArgumentException: The given column index '28' is not within the allowed range of [1,27].
                at org.akaza.openclinica.dao.core.EntityDAO.getColumnType(EntityDAO.java:638)
                at org.akaza.openclinica.dao.core.EntityDAO.processCurrentRow(EntityDAO.java:552)
                at org.akaza.openclinica.dao.core.EntityDAO.processResultRows(EntityDAO.java:534)
                at org.akaza.openclinica.dao.core.EntityDAO.select(EntityDAO.java:234)
                at org.akaza.openclinica.dao.core.EntityDAO.select(EntityDAO.java:186)
                at org.akaza.openclinica.dao.core.EntityDAO.select(EntityDAO.java:180)
                at org.akaza.openclinica.dao.login.UserAccountDAO.findByUserName(UserAccountDAO.java:520)
                at org.akaza.openclinica.web.filter.OpenClinicaUsernamePasswordAuthenticationFilter.attemptAuthentication(OpenClinicaUsernamePasswordAuthenticationFilter.java:130)`
etc

**Comment by toskrip** [comment]
OK, ws 1.1.0 will be only compatible to run with web 1.1.0 because a newer version contains DB changes (added for 2fa support).

If you would want to downgrade web to 1.1.0 you would have to manually rollback the DB changes using liquibase before.

We have library issues with build and deployment of ws 1.2.x which I will try to clean up so that we can get compatible ws deployables.
